// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.caitou.protocol;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.Frame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    boolean hasHeader();
    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    com.caitou.protocol.Protocol.Header getHeader();
    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    com.caitou.protocol.Protocol.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    com.caitou.protocol.RequestProto.Request getRequest();
    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    com.caitou.protocol.RequestProto.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    com.caitou.protocol.ResponseProto.Response getResponse();
    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    com.caitou.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.Frame}
   */
  public static final class Frame extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.Frame)
      FrameOrBuilder {
    // Use Frame.newBuilder() to construct.
    private Frame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Frame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Frame defaultInstance;
    public static Frame getDefaultInstance() {
      return defaultInstance;
    }

    public Frame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.caitou.protocol.Protocol.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.caitou.protocol.Protocol.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.caitou.protocol.RequestProto.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.caitou.protocol.RequestProto.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.caitou.protocol.ResponseProto.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.caitou.protocol.ResponseProto.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Frame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.Protocol.Frame.class, com.caitou.protocol.Protocol.Frame.Builder.class);
    }

    public static com.google.protobuf.Parser<Frame> PARSER =
        new com.google.protobuf.AbstractParser<Frame>() {
      public Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Frame> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private com.caitou.protocol.Protocol.Header header_;
    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    public com.caitou.protocol.Protocol.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .com.caitou.protocol.Header header = 1;</code>
     *
     * <pre>
     *消息头
     * </pre>
     */
    public com.caitou.protocol.Protocol.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private com.caitou.protocol.RequestProto.Request request_;
    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    public com.caitou.protocol.RequestProto.Request getRequest() {
      return request_;
    }
    /**
     * <code>optional .com.caitou.protocol.Request request = 2;</code>
     */
    public com.caitou.protocol.RequestProto.RequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 3;
    private com.caitou.protocol.ResponseProto.Response response_;
    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    public com.caitou.protocol.ResponseProto.Response getResponse() {
      return response_;
    }
    /**
     * <code>optional .com.caitou.protocol.Response response = 3;</code>
     */
    public com.caitou.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder() {
      return response_;
    }

    private void initFields() {
      header_ = com.caitou.protocol.Protocol.Header.getDefaultInstance();
      request_ = com.caitou.protocol.RequestProto.Request.getDefaultInstance();
      response_ = com.caitou.protocol.ResponseProto.Response.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, response_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.Protocol.Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.Protocol.Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.Protocol.Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.Protocol.Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.Frame)
        com.caitou.protocol.Protocol.FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Frame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.Protocol.Frame.class, com.caitou.protocol.Protocol.Frame.Builder.class);
      }

      // Construct using com.caitou.protocol.Protocol.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = com.caitou.protocol.Protocol.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestBuilder_ == null) {
          request_ = com.caitou.protocol.RequestProto.Request.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (responseBuilder_ == null) {
          response_ = com.caitou.protocol.ResponseProto.Response.getDefaultInstance();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Frame_descriptor;
      }

      public com.caitou.protocol.Protocol.Frame getDefaultInstanceForType() {
        return com.caitou.protocol.Protocol.Frame.getDefaultInstance();
      }

      public com.caitou.protocol.Protocol.Frame build() {
        com.caitou.protocol.Protocol.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.Protocol.Frame buildPartial() {
        com.caitou.protocol.Protocol.Frame result = new com.caitou.protocol.Protocol.Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.Protocol.Frame) {
          return mergeFrom((com.caitou.protocol.Protocol.Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.Protocol.Frame other) {
        if (other == com.caitou.protocol.Protocol.Frame.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.Protocol.Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.Protocol.Frame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.caitou.protocol.Protocol.Header header_ = com.caitou.protocol.Protocol.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.Protocol.Header, com.caitou.protocol.Protocol.Header.Builder, com.caitou.protocol.Protocol.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public com.caitou.protocol.Protocol.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public Builder setHeader(com.caitou.protocol.Protocol.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public Builder setHeader(
          com.caitou.protocol.Protocol.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public Builder mergeHeader(com.caitou.protocol.Protocol.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != com.caitou.protocol.Protocol.Header.getDefaultInstance()) {
            header_ =
              com.caitou.protocol.Protocol.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.caitou.protocol.Protocol.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public com.caitou.protocol.Protocol.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      public com.caitou.protocol.Protocol.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .com.caitou.protocol.Header header = 1;</code>
       *
       * <pre>
       *消息头
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.Protocol.Header, com.caitou.protocol.Protocol.Header.Builder, com.caitou.protocol.Protocol.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.Protocol.Header, com.caitou.protocol.Protocol.Header.Builder, com.caitou.protocol.Protocol.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.caitou.protocol.RequestProto.Request request_ = com.caitou.protocol.RequestProto.Request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.Request, com.caitou.protocol.RequestProto.Request.Builder, com.caitou.protocol.RequestProto.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public com.caitou.protocol.RequestProto.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public Builder setRequest(com.caitou.protocol.RequestProto.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public Builder setRequest(
          com.caitou.protocol.RequestProto.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public Builder mergeRequest(com.caitou.protocol.RequestProto.Request value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              request_ != com.caitou.protocol.RequestProto.Request.getDefaultInstance()) {
            request_ =
              com.caitou.protocol.RequestProto.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.caitou.protocol.RequestProto.Request.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public com.caitou.protocol.RequestProto.Request.Builder getRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      public com.caitou.protocol.RequestProto.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.Request request = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.Request, com.caitou.protocol.RequestProto.Request.Builder, com.caitou.protocol.RequestProto.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.RequestProto.Request, com.caitou.protocol.RequestProto.Request.Builder, com.caitou.protocol.RequestProto.RequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private com.caitou.protocol.ResponseProto.Response response_ = com.caitou.protocol.ResponseProto.Response.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.Response, com.caitou.protocol.ResponseProto.Response.Builder, com.caitou.protocol.ResponseProto.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public com.caitou.protocol.ResponseProto.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public Builder setResponse(com.caitou.protocol.ResponseProto.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public Builder setResponse(
          com.caitou.protocol.ResponseProto.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public Builder mergeResponse(com.caitou.protocol.ResponseProto.Response value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              response_ != com.caitou.protocol.ResponseProto.Response.getDefaultInstance()) {
            response_ =
              com.caitou.protocol.ResponseProto.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = com.caitou.protocol.ResponseProto.Response.getDefaultInstance();
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public com.caitou.protocol.ResponseProto.Response.Builder getResponseBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      public com.caitou.protocol.ResponseProto.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.Response response = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.Response, com.caitou.protocol.ResponseProto.Response.Builder, com.caitou.protocol.ResponseProto.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.ResponseProto.Response, com.caitou.protocol.ResponseProto.Response.Builder, com.caitou.protocol.ResponseProto.ResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.Frame)
    }

    static {
      defaultInstance = new Frame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.Frame)
  }

  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 head = 1;</code>
     *
     * <pre>
     *帧头
     * </pre>
     */
    boolean hasHead();
    /**
     * <code>required int32 head = 1;</code>
     *
     * <pre>
     *帧头
     * </pre>
     */
    int getHead();

    /**
     * <code>required int32 controlCode = 2;</code>
     */
    boolean hasControlCode();
    /**
     * <code>required int32 controlCode = 2;</code>
     */
    int getControlCode();

    /**
     * <code>required int32 functionCode = 3;</code>
     */
    boolean hasFunctionCode();
    /**
     * <code>required int32 functionCode = 3;</code>
     */
    int getFunctionCode();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.Header}
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.Header)
      HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }

    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              head_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              controlCode_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              functionCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.Protocol.Header.class, com.caitou.protocol.Protocol.Header.Builder.class);
    }

    public static com.google.protobuf.Parser<Header> PARSER =
        new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private int head_;
    /**
     * <code>required int32 head = 1;</code>
     *
     * <pre>
     *帧头
     * </pre>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 head = 1;</code>
     *
     * <pre>
     *帧头
     * </pre>
     */
    public int getHead() {
      return head_;
    }

    public static final int CONTROLCODE_FIELD_NUMBER = 2;
    private int controlCode_;
    /**
     * <code>required int32 controlCode = 2;</code>
     */
    public boolean hasControlCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 controlCode = 2;</code>
     */
    public int getControlCode() {
      return controlCode_;
    }

    public static final int FUNCTIONCODE_FIELD_NUMBER = 3;
    private int functionCode_;
    /**
     * <code>required int32 functionCode = 3;</code>
     */
    public boolean hasFunctionCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 functionCode = 3;</code>
     */
    public int getFunctionCode() {
      return functionCode_;
    }

    private void initFields() {
      head_ = 0;
      controlCode_ = 0;
      functionCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasControlCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunctionCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, controlCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, functionCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, controlCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, functionCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.Protocol.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.Protocol.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.Protocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.Protocol.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.Header)
        com.caitou.protocol.Protocol.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.Protocol.Header.class, com.caitou.protocol.Protocol.Header.Builder.class);
      }

      // Construct using com.caitou.protocol.Protocol.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        head_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        controlCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        functionCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.Protocol.internal_static_com_caitou_protocol_Header_descriptor;
      }

      public com.caitou.protocol.Protocol.Header getDefaultInstanceForType() {
        return com.caitou.protocol.Protocol.Header.getDefaultInstance();
      }

      public com.caitou.protocol.Protocol.Header build() {
        com.caitou.protocol.Protocol.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.Protocol.Header buildPartial() {
        com.caitou.protocol.Protocol.Header result = new com.caitou.protocol.Protocol.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.head_ = head_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.controlCode_ = controlCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.functionCode_ = functionCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.Protocol.Header) {
          return mergeFrom((com.caitou.protocol.Protocol.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.Protocol.Header other) {
        if (other == com.caitou.protocol.Protocol.Header.getDefaultInstance()) return this;
        if (other.hasHead()) {
          setHead(other.getHead());
        }
        if (other.hasControlCode()) {
          setControlCode(other.getControlCode());
        }
        if (other.hasFunctionCode()) {
          setFunctionCode(other.getFunctionCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {
          
          return false;
        }
        if (!hasControlCode()) {
          
          return false;
        }
        if (!hasFunctionCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.Protocol.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.Protocol.Header) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int head_ ;
      /**
       * <code>required int32 head = 1;</code>
       *
       * <pre>
       *帧头
       * </pre>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 head = 1;</code>
       *
       * <pre>
       *帧头
       * </pre>
       */
      public int getHead() {
        return head_;
      }
      /**
       * <code>required int32 head = 1;</code>
       *
       * <pre>
       *帧头
       * </pre>
       */
      public Builder setHead(int value) {
        bitField0_ |= 0x00000001;
        head_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 head = 1;</code>
       *
       * <pre>
       *帧头
       * </pre>
       */
      public Builder clearHead() {
        bitField0_ = (bitField0_ & ~0x00000001);
        head_ = 0;
        onChanged();
        return this;
      }

      private int controlCode_ ;
      /**
       * <code>required int32 controlCode = 2;</code>
       */
      public boolean hasControlCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 controlCode = 2;</code>
       */
      public int getControlCode() {
        return controlCode_;
      }
      /**
       * <code>required int32 controlCode = 2;</code>
       */
      public Builder setControlCode(int value) {
        bitField0_ |= 0x00000002;
        controlCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 controlCode = 2;</code>
       */
      public Builder clearControlCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        controlCode_ = 0;
        onChanged();
        return this;
      }

      private int functionCode_ ;
      /**
       * <code>required int32 functionCode = 3;</code>
       */
      public boolean hasFunctionCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 functionCode = 3;</code>
       */
      public int getFunctionCode() {
        return functionCode_;
      }
      /**
       * <code>required int32 functionCode = 3;</code>
       */
      public Builder setFunctionCode(int value) {
        bitField0_ |= 0x00000004;
        functionCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 functionCode = 3;</code>
       */
      public Builder clearFunctionCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        functionCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.Header)
    }

    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.Header)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_Frame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\022\023com.caitou.protocol\032\rr" +
      "equest.proto\032\016response.proto\"\224\001\n\005Frame\022+" +
      "\n\006header\030\001 \002(\0132\033.com.caitou.protocol.Hea" +
      "der\022-\n\007request\030\002 \001(\0132\034.com.caitou.protoc" +
      "ol.Request\022/\n\010response\030\003 \001(\0132\035.com.caito" +
      "u.protocol.Response\"A\n\006Header\022\014\n\004head\030\001 " +
      "\002(\005\022\023\n\013controlCode\030\002 \002(\005\022\024\n\014functionCode" +
      "\030\003 \002(\005B\037\n\023com.caitou.protocolB\010Protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.caitou.protocol.RequestProto.getDescriptor(),
          com.caitou.protocol.ResponseProto.getDescriptor(),
        }, assigner);
    internal_static_com_caitou_protocol_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caitou_protocol_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_Frame_descriptor,
        new java.lang.String[] { "Header", "Request", "Response", });
    internal_static_com_caitou_protocol_Header_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_caitou_protocol_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_Header_descriptor,
        new java.lang.String[] { "Head", "ControlCode", "FunctionCode", });
    com.caitou.protocol.RequestProto.getDescriptor();
    com.caitou.protocol.ResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
