// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.caitou.protocol;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    boolean hasStringRequest();
    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    com.caitou.protocol.RequestProto.StringRequest getStringRequest();
    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    com.caitou.protocol.RequestProto.StringRequestOrBuilder getStringRequestOrBuilder();

    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    boolean hasIntRequest();
    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    com.caitou.protocol.RequestProto.IntRequest getIntRequest();
    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    com.caitou.protocol.RequestProto.IntRequestOrBuilder getIntRequestOrBuilder();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.Request}
   *
   * <pre>
   *上行帧
   * </pre>
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.caitou.protocol.RequestProto.StringRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = stringRequest_.toBuilder();
              }
              stringRequest_ = input.readMessage(com.caitou.protocol.RequestProto.StringRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringRequest_);
                stringRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.caitou.protocol.RequestProto.IntRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = intRequest_.toBuilder();
              }
              intRequest_ = input.readMessage(com.caitou.protocol.RequestProto.IntRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(intRequest_);
                intRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.RequestProto.Request.class, com.caitou.protocol.RequestProto.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRINGREQUEST_FIELD_NUMBER = 1;
    private com.caitou.protocol.RequestProto.StringRequest stringRequest_;
    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    public boolean hasStringRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    public com.caitou.protocol.RequestProto.StringRequest getStringRequest() {
      return stringRequest_;
    }
    /**
     * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
     */
    public com.caitou.protocol.RequestProto.StringRequestOrBuilder getStringRequestOrBuilder() {
      return stringRequest_;
    }

    public static final int INTREQUEST_FIELD_NUMBER = 2;
    private com.caitou.protocol.RequestProto.IntRequest intRequest_;
    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    public boolean hasIntRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    public com.caitou.protocol.RequestProto.IntRequest getIntRequest() {
      return intRequest_;
    }
    /**
     * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
     */
    public com.caitou.protocol.RequestProto.IntRequestOrBuilder getIntRequestOrBuilder() {
      return intRequest_;
    }

    private void initFields() {
      stringRequest_ = com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance();
      intRequest_ = com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasStringRequest()) {
        if (!getStringRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasIntRequest()) {
        if (!getIntRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, stringRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, intRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stringRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, intRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.RequestProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.RequestProto.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.Request}
     *
     * <pre>
     *上行帧
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.Request)
        com.caitou.protocol.RequestProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.RequestProto.Request.class, com.caitou.protocol.RequestProto.Request.Builder.class);
      }

      // Construct using com.caitou.protocol.RequestProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStringRequestFieldBuilder();
          getIntRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (stringRequestBuilder_ == null) {
          stringRequest_ = com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance();
        } else {
          stringRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (intRequestBuilder_ == null) {
          intRequest_ = com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance();
        } else {
          intRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_Request_descriptor;
      }

      public com.caitou.protocol.RequestProto.Request getDefaultInstanceForType() {
        return com.caitou.protocol.RequestProto.Request.getDefaultInstance();
      }

      public com.caitou.protocol.RequestProto.Request build() {
        com.caitou.protocol.RequestProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.RequestProto.Request buildPartial() {
        com.caitou.protocol.RequestProto.Request result = new com.caitou.protocol.RequestProto.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (stringRequestBuilder_ == null) {
          result.stringRequest_ = stringRequest_;
        } else {
          result.stringRequest_ = stringRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (intRequestBuilder_ == null) {
          result.intRequest_ = intRequest_;
        } else {
          result.intRequest_ = intRequestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.RequestProto.Request) {
          return mergeFrom((com.caitou.protocol.RequestProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.RequestProto.Request other) {
        if (other == com.caitou.protocol.RequestProto.Request.getDefaultInstance()) return this;
        if (other.hasStringRequest()) {
          mergeStringRequest(other.getStringRequest());
        }
        if (other.hasIntRequest()) {
          mergeIntRequest(other.getIntRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasStringRequest()) {
          if (!getStringRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasIntRequest()) {
          if (!getIntRequest().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.RequestProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.RequestProto.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.caitou.protocol.RequestProto.StringRequest stringRequest_ = com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.StringRequest, com.caitou.protocol.RequestProto.StringRequest.Builder, com.caitou.protocol.RequestProto.StringRequestOrBuilder> stringRequestBuilder_;
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public boolean hasStringRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public com.caitou.protocol.RequestProto.StringRequest getStringRequest() {
        if (stringRequestBuilder_ == null) {
          return stringRequest_;
        } else {
          return stringRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public Builder setStringRequest(com.caitou.protocol.RequestProto.StringRequest value) {
        if (stringRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringRequest_ = value;
          onChanged();
        } else {
          stringRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public Builder setStringRequest(
          com.caitou.protocol.RequestProto.StringRequest.Builder builderForValue) {
        if (stringRequestBuilder_ == null) {
          stringRequest_ = builderForValue.build();
          onChanged();
        } else {
          stringRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public Builder mergeStringRequest(com.caitou.protocol.RequestProto.StringRequest value) {
        if (stringRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              stringRequest_ != com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance()) {
            stringRequest_ =
              com.caitou.protocol.RequestProto.StringRequest.newBuilder(stringRequest_).mergeFrom(value).buildPartial();
          } else {
            stringRequest_ = value;
          }
          onChanged();
        } else {
          stringRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public Builder clearStringRequest() {
        if (stringRequestBuilder_ == null) {
          stringRequest_ = com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance();
          onChanged();
        } else {
          stringRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public com.caitou.protocol.RequestProto.StringRequest.Builder getStringRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStringRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      public com.caitou.protocol.RequestProto.StringRequestOrBuilder getStringRequestOrBuilder() {
        if (stringRequestBuilder_ != null) {
          return stringRequestBuilder_.getMessageOrBuilder();
        } else {
          return stringRequest_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.StringRequest stringRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.StringRequest, com.caitou.protocol.RequestProto.StringRequest.Builder, com.caitou.protocol.RequestProto.StringRequestOrBuilder> 
          getStringRequestFieldBuilder() {
        if (stringRequestBuilder_ == null) {
          stringRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.RequestProto.StringRequest, com.caitou.protocol.RequestProto.StringRequest.Builder, com.caitou.protocol.RequestProto.StringRequestOrBuilder>(
                  getStringRequest(),
                  getParentForChildren(),
                  isClean());
          stringRequest_ = null;
        }
        return stringRequestBuilder_;
      }

      private com.caitou.protocol.RequestProto.IntRequest intRequest_ = com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.IntRequest, com.caitou.protocol.RequestProto.IntRequest.Builder, com.caitou.protocol.RequestProto.IntRequestOrBuilder> intRequestBuilder_;
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public boolean hasIntRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public com.caitou.protocol.RequestProto.IntRequest getIntRequest() {
        if (intRequestBuilder_ == null) {
          return intRequest_;
        } else {
          return intRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public Builder setIntRequest(com.caitou.protocol.RequestProto.IntRequest value) {
        if (intRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          intRequest_ = value;
          onChanged();
        } else {
          intRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public Builder setIntRequest(
          com.caitou.protocol.RequestProto.IntRequest.Builder builderForValue) {
        if (intRequestBuilder_ == null) {
          intRequest_ = builderForValue.build();
          onChanged();
        } else {
          intRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public Builder mergeIntRequest(com.caitou.protocol.RequestProto.IntRequest value) {
        if (intRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              intRequest_ != com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance()) {
            intRequest_ =
              com.caitou.protocol.RequestProto.IntRequest.newBuilder(intRequest_).mergeFrom(value).buildPartial();
          } else {
            intRequest_ = value;
          }
          onChanged();
        } else {
          intRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public Builder clearIntRequest() {
        if (intRequestBuilder_ == null) {
          intRequest_ = com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance();
          onChanged();
        } else {
          intRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public com.caitou.protocol.RequestProto.IntRequest.Builder getIntRequestBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIntRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      public com.caitou.protocol.RequestProto.IntRequestOrBuilder getIntRequestOrBuilder() {
        if (intRequestBuilder_ != null) {
          return intRequestBuilder_.getMessageOrBuilder();
        } else {
          return intRequest_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.IntRequest intRequest = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.RequestProto.IntRequest, com.caitou.protocol.RequestProto.IntRequest.Builder, com.caitou.protocol.RequestProto.IntRequestOrBuilder> 
          getIntRequestFieldBuilder() {
        if (intRequestBuilder_ == null) {
          intRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.RequestProto.IntRequest, com.caitou.protocol.RequestProto.IntRequest.Builder, com.caitou.protocol.RequestProto.IntRequestOrBuilder>(
                  getIntRequest(),
                  getParentForChildren(),
                  isClean());
          intRequest_ = null;
        }
        return intRequestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.Request)
  }

  public interface StringRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.StringRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string StrData = 1;</code>
     */
    boolean hasStrData();
    /**
     * <code>required string StrData = 1;</code>
     */
    java.lang.String getStrData();
    /**
     * <code>required string StrData = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrDataBytes();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.StringRequest}
   *
   * <pre>
   *字符串类型数据
   * </pre>
   */
  public static final class StringRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.StringRequest)
      StringRequestOrBuilder {
    // Use StringRequest.newBuilder() to construct.
    private StringRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringRequest defaultInstance;
    public static StringRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StringRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strData_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_StringRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_StringRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.RequestProto.StringRequest.class, com.caitou.protocol.RequestProto.StringRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StringRequest> PARSER =
        new com.google.protobuf.AbstractParser<StringRequest>() {
      public StringRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StringRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRDATA_FIELD_NUMBER = 1;
    private java.lang.Object strData_;
    /**
     * <code>required string StrData = 1;</code>
     */
    public boolean hasStrData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string StrData = 1;</code>
     */
    public java.lang.String getStrData() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string StrData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrDataBytes() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      strData_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.StringRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.RequestProto.StringRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.StringRequest}
     *
     * <pre>
     *字符串类型数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.StringRequest)
        com.caitou.protocol.RequestProto.StringRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_StringRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_StringRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.RequestProto.StringRequest.class, com.caitou.protocol.RequestProto.StringRequest.Builder.class);
      }

      // Construct using com.caitou.protocol.RequestProto.StringRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        strData_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_StringRequest_descriptor;
      }

      public com.caitou.protocol.RequestProto.StringRequest getDefaultInstanceForType() {
        return com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance();
      }

      public com.caitou.protocol.RequestProto.StringRequest build() {
        com.caitou.protocol.RequestProto.StringRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.RequestProto.StringRequest buildPartial() {
        com.caitou.protocol.RequestProto.StringRequest result = new com.caitou.protocol.RequestProto.StringRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strData_ = strData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.RequestProto.StringRequest) {
          return mergeFrom((com.caitou.protocol.RequestProto.StringRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.RequestProto.StringRequest other) {
        if (other == com.caitou.protocol.RequestProto.StringRequest.getDefaultInstance()) return this;
        if (other.hasStrData()) {
          bitField0_ |= 0x00000001;
          strData_ = other.strData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStrData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.RequestProto.StringRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.RequestProto.StringRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strData_ = "";
      /**
       * <code>required string StrData = 1;</code>
       */
      public boolean hasStrData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string StrData = 1;</code>
       */
      public java.lang.String getStrData() {
        java.lang.Object ref = strData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string StrData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrDataBytes() {
        java.lang.Object ref = strData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string StrData = 1;</code>
       */
      public Builder setStrData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string StrData = 1;</code>
       */
      public Builder clearStrData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strData_ = getDefaultInstance().getStrData();
        onChanged();
        return this;
      }
      /**
       * <code>required string StrData = 1;</code>
       */
      public Builder setStrDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strData_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.StringRequest)
    }

    static {
      defaultInstance = new StringRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.StringRequest)
  }

  public interface IntRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.IntRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 int32Data = 1;</code>
     */
    boolean hasInt32Data();
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    int getInt32Data();

    /**
     * <code>required int64 int64Data = 2;</code>
     */
    boolean hasInt64Data();
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    long getInt64Data();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.IntRequest}
   *
   * <pre>
   *整型数据
   * </pre>
   */
  public static final class IntRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.IntRequest)
      IntRequestOrBuilder {
    // Use IntRequest.newBuilder() to construct.
    private IntRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IntRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IntRequest defaultInstance;
    public static IntRequest getDefaultInstance() {
      return defaultInstance;
    }

    public IntRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IntRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              int32Data_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              int64Data_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_IntRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_IntRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.RequestProto.IntRequest.class, com.caitou.protocol.RequestProto.IntRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<IntRequest> PARSER =
        new com.google.protobuf.AbstractParser<IntRequest>() {
      public IntRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IntRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INT32DATA_FIELD_NUMBER = 1;
    private int int32Data_;
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    public boolean hasInt32Data() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    public int getInt32Data() {
      return int32Data_;
    }

    public static final int INT64DATA_FIELD_NUMBER = 2;
    private long int64Data_;
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    public boolean hasInt64Data() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    public long getInt64Data() {
      return int64Data_;
    }

    private void initFields() {
      int32Data_ = 0;
      int64Data_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInt32Data()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInt64Data()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, int32Data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, int64Data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, int32Data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, int64Data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.RequestProto.IntRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.RequestProto.IntRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.IntRequest}
     *
     * <pre>
     *整型数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.IntRequest)
        com.caitou.protocol.RequestProto.IntRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_IntRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_IntRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.RequestProto.IntRequest.class, com.caitou.protocol.RequestProto.IntRequest.Builder.class);
      }

      // Construct using com.caitou.protocol.RequestProto.IntRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        int32Data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        int64Data_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.RequestProto.internal_static_com_caitou_protocol_IntRequest_descriptor;
      }

      public com.caitou.protocol.RequestProto.IntRequest getDefaultInstanceForType() {
        return com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance();
      }

      public com.caitou.protocol.RequestProto.IntRequest build() {
        com.caitou.protocol.RequestProto.IntRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.RequestProto.IntRequest buildPartial() {
        com.caitou.protocol.RequestProto.IntRequest result = new com.caitou.protocol.RequestProto.IntRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.int32Data_ = int32Data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.int64Data_ = int64Data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.RequestProto.IntRequest) {
          return mergeFrom((com.caitou.protocol.RequestProto.IntRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.RequestProto.IntRequest other) {
        if (other == com.caitou.protocol.RequestProto.IntRequest.getDefaultInstance()) return this;
        if (other.hasInt32Data()) {
          setInt32Data(other.getInt32Data());
        }
        if (other.hasInt64Data()) {
          setInt64Data(other.getInt64Data());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInt32Data()) {
          
          return false;
        }
        if (!hasInt64Data()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.RequestProto.IntRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.RequestProto.IntRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int int32Data_ ;
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public boolean hasInt32Data() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public int getInt32Data() {
        return int32Data_;
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public Builder setInt32Data(int value) {
        bitField0_ |= 0x00000001;
        int32Data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public Builder clearInt32Data() {
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Data_ = 0;
        onChanged();
        return this;
      }

      private long int64Data_ ;
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public boolean hasInt64Data() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public long getInt64Data() {
        return int64Data_;
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public Builder setInt64Data(long value) {
        bitField0_ |= 0x00000002;
        int64Data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public Builder clearInt64Data() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int64Data_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.IntRequest)
    }

    static {
      defaultInstance = new IntRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.IntRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_StringRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_StringRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_IntRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_IntRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\023com.caitou.protocol\"y\n\007" +
      "Request\0229\n\rstringRequest\030\001 \001(\0132\".com.cai" +
      "tou.protocol.StringRequest\0223\n\nintRequest" +
      "\030\002 \001(\0132\037.com.caitou.protocol.IntRequest\"" +
      " \n\rStringRequest\022\017\n\007StrData\030\001 \002(\t\"2\n\nInt" +
      "Request\022\021\n\tint32Data\030\001 \002(\005\022\021\n\tint64Data\030" +
      "\002 \002(\003B#\n\023com.caitou.protocolB\014RequestPro" +
      "to"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_caitou_protocol_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caitou_protocol_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_Request_descriptor,
        new java.lang.String[] { "StringRequest", "IntRequest", });
    internal_static_com_caitou_protocol_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_caitou_protocol_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_StringRequest_descriptor,
        new java.lang.String[] { "StrData", });
    internal_static_com_caitou_protocol_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_caitou_protocol_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_IntRequest_descriptor,
        new java.lang.String[] { "Int32Data", "Int64Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
