// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.caitou.protocol;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    boolean hasIntResponse();
    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    com.caitou.protocol.ResponseProto.IntResponse getIntResponse();
    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    com.caitou.protocol.ResponseProto.IntResponseOrBuilder getIntResponseOrBuilder();

    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    boolean hasStringResponse();
    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    com.caitou.protocol.ResponseProto.StringResponse getStringResponse();
    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    com.caitou.protocol.ResponseProto.StringResponseOrBuilder getStringResponseOrBuilder();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.Response}
   *
   * <pre>
   *下行帧
   * </pre>
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.caitou.protocol.ResponseProto.IntResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = intResponse_.toBuilder();
              }
              intResponse_ = input.readMessage(com.caitou.protocol.ResponseProto.IntResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(intResponse_);
                intResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.caitou.protocol.ResponseProto.StringResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = stringResponse_.toBuilder();
              }
              stringResponse_ = input.readMessage(com.caitou.protocol.ResponseProto.StringResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stringResponse_);
                stringResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.ResponseProto.Response.class, com.caitou.protocol.ResponseProto.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INTRESPONSE_FIELD_NUMBER = 1;
    private com.caitou.protocol.ResponseProto.IntResponse intResponse_;
    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    public boolean hasIntResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    public com.caitou.protocol.ResponseProto.IntResponse getIntResponse() {
      return intResponse_;
    }
    /**
     * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
     */
    public com.caitou.protocol.ResponseProto.IntResponseOrBuilder getIntResponseOrBuilder() {
      return intResponse_;
    }

    public static final int STRINGRESPONSE_FIELD_NUMBER = 2;
    private com.caitou.protocol.ResponseProto.StringResponse stringResponse_;
    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    public boolean hasStringResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    public com.caitou.protocol.ResponseProto.StringResponse getStringResponse() {
      return stringResponse_;
    }
    /**
     * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
     */
    public com.caitou.protocol.ResponseProto.StringResponseOrBuilder getStringResponseOrBuilder() {
      return stringResponse_;
    }

    private void initFields() {
      intResponse_ = com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance();
      stringResponse_ = com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasIntResponse()) {
        if (!getIntResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStringResponse()) {
        if (!getStringResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, intResponse_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, stringResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, intResponse_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, stringResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.ResponseProto.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.Response}
     *
     * <pre>
     *下行帧
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.Response)
        com.caitou.protocol.ResponseProto.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.ResponseProto.Response.class, com.caitou.protocol.ResponseProto.Response.Builder.class);
      }

      // Construct using com.caitou.protocol.ResponseProto.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIntResponseFieldBuilder();
          getStringResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (intResponseBuilder_ == null) {
          intResponse_ = com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance();
        } else {
          intResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (stringResponseBuilder_ == null) {
          stringResponse_ = com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance();
        } else {
          stringResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_Response_descriptor;
      }

      public com.caitou.protocol.ResponseProto.Response getDefaultInstanceForType() {
        return com.caitou.protocol.ResponseProto.Response.getDefaultInstance();
      }

      public com.caitou.protocol.ResponseProto.Response build() {
        com.caitou.protocol.ResponseProto.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.ResponseProto.Response buildPartial() {
        com.caitou.protocol.ResponseProto.Response result = new com.caitou.protocol.ResponseProto.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (intResponseBuilder_ == null) {
          result.intResponse_ = intResponse_;
        } else {
          result.intResponse_ = intResponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (stringResponseBuilder_ == null) {
          result.stringResponse_ = stringResponse_;
        } else {
          result.stringResponse_ = stringResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.ResponseProto.Response) {
          return mergeFrom((com.caitou.protocol.ResponseProto.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.ResponseProto.Response other) {
        if (other == com.caitou.protocol.ResponseProto.Response.getDefaultInstance()) return this;
        if (other.hasIntResponse()) {
          mergeIntResponse(other.getIntResponse());
        }
        if (other.hasStringResponse()) {
          mergeStringResponse(other.getStringResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasIntResponse()) {
          if (!getIntResponse().isInitialized()) {
            
            return false;
          }
        }
        if (hasStringResponse()) {
          if (!getStringResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.ResponseProto.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.ResponseProto.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.caitou.protocol.ResponseProto.IntResponse intResponse_ = com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.IntResponse, com.caitou.protocol.ResponseProto.IntResponse.Builder, com.caitou.protocol.ResponseProto.IntResponseOrBuilder> intResponseBuilder_;
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public boolean hasIntResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public com.caitou.protocol.ResponseProto.IntResponse getIntResponse() {
        if (intResponseBuilder_ == null) {
          return intResponse_;
        } else {
          return intResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public Builder setIntResponse(com.caitou.protocol.ResponseProto.IntResponse value) {
        if (intResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          intResponse_ = value;
          onChanged();
        } else {
          intResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public Builder setIntResponse(
          com.caitou.protocol.ResponseProto.IntResponse.Builder builderForValue) {
        if (intResponseBuilder_ == null) {
          intResponse_ = builderForValue.build();
          onChanged();
        } else {
          intResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public Builder mergeIntResponse(com.caitou.protocol.ResponseProto.IntResponse value) {
        if (intResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              intResponse_ != com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance()) {
            intResponse_ =
              com.caitou.protocol.ResponseProto.IntResponse.newBuilder(intResponse_).mergeFrom(value).buildPartial();
          } else {
            intResponse_ = value;
          }
          onChanged();
        } else {
          intResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public Builder clearIntResponse() {
        if (intResponseBuilder_ == null) {
          intResponse_ = com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance();
          onChanged();
        } else {
          intResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public com.caitou.protocol.ResponseProto.IntResponse.Builder getIntResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIntResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      public com.caitou.protocol.ResponseProto.IntResponseOrBuilder getIntResponseOrBuilder() {
        if (intResponseBuilder_ != null) {
          return intResponseBuilder_.getMessageOrBuilder();
        } else {
          return intResponse_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.IntResponse intResponse = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.IntResponse, com.caitou.protocol.ResponseProto.IntResponse.Builder, com.caitou.protocol.ResponseProto.IntResponseOrBuilder> 
          getIntResponseFieldBuilder() {
        if (intResponseBuilder_ == null) {
          intResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.ResponseProto.IntResponse, com.caitou.protocol.ResponseProto.IntResponse.Builder, com.caitou.protocol.ResponseProto.IntResponseOrBuilder>(
                  getIntResponse(),
                  getParentForChildren(),
                  isClean());
          intResponse_ = null;
        }
        return intResponseBuilder_;
      }

      private com.caitou.protocol.ResponseProto.StringResponse stringResponse_ = com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.StringResponse, com.caitou.protocol.ResponseProto.StringResponse.Builder, com.caitou.protocol.ResponseProto.StringResponseOrBuilder> stringResponseBuilder_;
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public boolean hasStringResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public com.caitou.protocol.ResponseProto.StringResponse getStringResponse() {
        if (stringResponseBuilder_ == null) {
          return stringResponse_;
        } else {
          return stringResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public Builder setStringResponse(com.caitou.protocol.ResponseProto.StringResponse value) {
        if (stringResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stringResponse_ = value;
          onChanged();
        } else {
          stringResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public Builder setStringResponse(
          com.caitou.protocol.ResponseProto.StringResponse.Builder builderForValue) {
        if (stringResponseBuilder_ == null) {
          stringResponse_ = builderForValue.build();
          onChanged();
        } else {
          stringResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public Builder mergeStringResponse(com.caitou.protocol.ResponseProto.StringResponse value) {
        if (stringResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              stringResponse_ != com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance()) {
            stringResponse_ =
              com.caitou.protocol.ResponseProto.StringResponse.newBuilder(stringResponse_).mergeFrom(value).buildPartial();
          } else {
            stringResponse_ = value;
          }
          onChanged();
        } else {
          stringResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public Builder clearStringResponse() {
        if (stringResponseBuilder_ == null) {
          stringResponse_ = com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance();
          onChanged();
        } else {
          stringResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public com.caitou.protocol.ResponseProto.StringResponse.Builder getStringResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStringResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      public com.caitou.protocol.ResponseProto.StringResponseOrBuilder getStringResponseOrBuilder() {
        if (stringResponseBuilder_ != null) {
          return stringResponseBuilder_.getMessageOrBuilder();
        } else {
          return stringResponse_;
        }
      }
      /**
       * <code>optional .com.caitou.protocol.StringResponse stringResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.caitou.protocol.ResponseProto.StringResponse, com.caitou.protocol.ResponseProto.StringResponse.Builder, com.caitou.protocol.ResponseProto.StringResponseOrBuilder> 
          getStringResponseFieldBuilder() {
        if (stringResponseBuilder_ == null) {
          stringResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.caitou.protocol.ResponseProto.StringResponse, com.caitou.protocol.ResponseProto.StringResponse.Builder, com.caitou.protocol.ResponseProto.StringResponseOrBuilder>(
                  getStringResponse(),
                  getParentForChildren(),
                  isClean());
          stringResponse_ = null;
        }
        return stringResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.Response)
  }

  public interface IntResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.IntResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 int32Data = 1;</code>
     */
    boolean hasInt32Data();
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    int getInt32Data();

    /**
     * <code>required int64 int64Data = 2;</code>
     */
    boolean hasInt64Data();
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    long getInt64Data();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.IntResponse}
   *
   * <pre>
   *整型数据回复
   * </pre>
   */
  public static final class IntResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.IntResponse)
      IntResponseOrBuilder {
    // Use IntResponse.newBuilder() to construct.
    private IntResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private IntResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final IntResponse defaultInstance;
    public static IntResponse getDefaultInstance() {
      return defaultInstance;
    }

    public IntResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private IntResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              int32Data_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              int64Data_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_IntResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_IntResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.ResponseProto.IntResponse.class, com.caitou.protocol.ResponseProto.IntResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<IntResponse> PARSER =
        new com.google.protobuf.AbstractParser<IntResponse>() {
      public IntResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IntResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int INT32DATA_FIELD_NUMBER = 1;
    private int int32Data_;
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    public boolean hasInt32Data() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 int32Data = 1;</code>
     */
    public int getInt32Data() {
      return int32Data_;
    }

    public static final int INT64DATA_FIELD_NUMBER = 2;
    private long int64Data_;
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    public boolean hasInt64Data() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 int64Data = 2;</code>
     */
    public long getInt64Data() {
      return int64Data_;
    }

    private void initFields() {
      int32Data_ = 0;
      int64Data_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasInt32Data()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInt64Data()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, int32Data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, int64Data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, int32Data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, int64Data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.IntResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.ResponseProto.IntResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.IntResponse}
     *
     * <pre>
     *整型数据回复
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.IntResponse)
        com.caitou.protocol.ResponseProto.IntResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_IntResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_IntResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.ResponseProto.IntResponse.class, com.caitou.protocol.ResponseProto.IntResponse.Builder.class);
      }

      // Construct using com.caitou.protocol.ResponseProto.IntResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        int32Data_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        int64Data_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_IntResponse_descriptor;
      }

      public com.caitou.protocol.ResponseProto.IntResponse getDefaultInstanceForType() {
        return com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance();
      }

      public com.caitou.protocol.ResponseProto.IntResponse build() {
        com.caitou.protocol.ResponseProto.IntResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.ResponseProto.IntResponse buildPartial() {
        com.caitou.protocol.ResponseProto.IntResponse result = new com.caitou.protocol.ResponseProto.IntResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.int32Data_ = int32Data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.int64Data_ = int64Data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.ResponseProto.IntResponse) {
          return mergeFrom((com.caitou.protocol.ResponseProto.IntResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.ResponseProto.IntResponse other) {
        if (other == com.caitou.protocol.ResponseProto.IntResponse.getDefaultInstance()) return this;
        if (other.hasInt32Data()) {
          setInt32Data(other.getInt32Data());
        }
        if (other.hasInt64Data()) {
          setInt64Data(other.getInt64Data());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInt32Data()) {
          
          return false;
        }
        if (!hasInt64Data()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.ResponseProto.IntResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.ResponseProto.IntResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int int32Data_ ;
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public boolean hasInt32Data() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public int getInt32Data() {
        return int32Data_;
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public Builder setInt32Data(int value) {
        bitField0_ |= 0x00000001;
        int32Data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 int32Data = 1;</code>
       */
      public Builder clearInt32Data() {
        bitField0_ = (bitField0_ & ~0x00000001);
        int32Data_ = 0;
        onChanged();
        return this;
      }

      private long int64Data_ ;
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public boolean hasInt64Data() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public long getInt64Data() {
        return int64Data_;
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public Builder setInt64Data(long value) {
        bitField0_ |= 0x00000002;
        int64Data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 int64Data = 2;</code>
       */
      public Builder clearInt64Data() {
        bitField0_ = (bitField0_ & ~0x00000002);
        int64Data_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.IntResponse)
    }

    static {
      defaultInstance = new IntResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.IntResponse)
  }

  public interface StringResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.caitou.protocol.StringResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string strData = 1;</code>
     */
    boolean hasStrData();
    /**
     * <code>required string strData = 1;</code>
     */
    java.lang.String getStrData();
    /**
     * <code>required string strData = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrDataBytes();
  }
  /**
   * Protobuf type {@code com.caitou.protocol.StringResponse}
   *
   * <pre>
   *字符串型数据回复
   * </pre>
   */
  public static final class StringResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.caitou.protocol.StringResponse)
      StringResponseOrBuilder {
    // Use StringResponse.newBuilder() to construct.
    private StringResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringResponse defaultInstance;
    public static StringResponse getDefaultInstance() {
      return defaultInstance;
    }

    public StringResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              strData_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_StringResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_StringResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caitou.protocol.ResponseProto.StringResponse.class, com.caitou.protocol.ResponseProto.StringResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<StringResponse> PARSER =
        new com.google.protobuf.AbstractParser<StringResponse>() {
      public StringResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StringResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STRDATA_FIELD_NUMBER = 1;
    private java.lang.Object strData_;
    /**
     * <code>required string strData = 1;</code>
     */
    public boolean hasStrData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string strData = 1;</code>
     */
    public java.lang.String getStrData() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strData_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string strData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrDataBytes() {
      java.lang.Object ref = strData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      strData_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStrData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getStrDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getStrDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caitou.protocol.ResponseProto.StringResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caitou.protocol.ResponseProto.StringResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caitou.protocol.StringResponse}
     *
     * <pre>
     *字符串型数据回复
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.caitou.protocol.StringResponse)
        com.caitou.protocol.ResponseProto.StringResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_StringResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_StringResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caitou.protocol.ResponseProto.StringResponse.class, com.caitou.protocol.ResponseProto.StringResponse.Builder.class);
      }

      // Construct using com.caitou.protocol.ResponseProto.StringResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        strData_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caitou.protocol.ResponseProto.internal_static_com_caitou_protocol_StringResponse_descriptor;
      }

      public com.caitou.protocol.ResponseProto.StringResponse getDefaultInstanceForType() {
        return com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance();
      }

      public com.caitou.protocol.ResponseProto.StringResponse build() {
        com.caitou.protocol.ResponseProto.StringResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caitou.protocol.ResponseProto.StringResponse buildPartial() {
        com.caitou.protocol.ResponseProto.StringResponse result = new com.caitou.protocol.ResponseProto.StringResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.strData_ = strData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caitou.protocol.ResponseProto.StringResponse) {
          return mergeFrom((com.caitou.protocol.ResponseProto.StringResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caitou.protocol.ResponseProto.StringResponse other) {
        if (other == com.caitou.protocol.ResponseProto.StringResponse.getDefaultInstance()) return this;
        if (other.hasStrData()) {
          bitField0_ |= 0x00000001;
          strData_ = other.strData_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStrData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caitou.protocol.ResponseProto.StringResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caitou.protocol.ResponseProto.StringResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object strData_ = "";
      /**
       * <code>required string strData = 1;</code>
       */
      public boolean hasStrData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string strData = 1;</code>
       */
      public java.lang.String getStrData() {
        java.lang.Object ref = strData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strData_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string strData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrDataBytes() {
        java.lang.Object ref = strData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string strData = 1;</code>
       */
      public Builder setStrData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string strData = 1;</code>
       */
      public Builder clearStrData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        strData_ = getDefaultInstance().getStrData();
        onChanged();
        return this;
      }
      /**
       * <code>required string strData = 1;</code>
       */
      public Builder setStrDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        strData_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caitou.protocol.StringResponse)
    }

    static {
      defaultInstance = new StringResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caitou.protocol.StringResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_IntResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_IntResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caitou_protocol_StringResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caitou_protocol_StringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\022\023com.caitou.protocol\"~\n" +
      "\010Response\0225\n\013intResponse\030\001 \001(\0132 .com.cai" +
      "tou.protocol.IntResponse\022;\n\016stringRespon" +
      "se\030\002 \001(\0132#.com.caitou.protocol.StringRes" +
      "ponse\"3\n\013IntResponse\022\021\n\tint32Data\030\001 \002(\005\022" +
      "\021\n\tint64Data\030\002 \002(\003\"!\n\016StringResponse\022\017\n\007" +
      "strData\030\001 \002(\tB$\n\023com.caitou.protocolB\rRe" +
      "sponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_caitou_protocol_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_caitou_protocol_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_Response_descriptor,
        new java.lang.String[] { "IntResponse", "StringResponse", });
    internal_static_com_caitou_protocol_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_caitou_protocol_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_IntResponse_descriptor,
        new java.lang.String[] { "Int32Data", "Int64Data", });
    internal_static_com_caitou_protocol_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_caitou_protocol_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_caitou_protocol_StringResponse_descriptor,
        new java.lang.String[] { "StrData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
